name: Build and Encode Surprise EXE

on:
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Set up CMake
        uses: jwlawson/actions-setup-cmake@v1

      - name: Build the EXE
        run: |
          cmake -B build .
          cmake --build build

      - name: Encode the EXE
        run: |
          python encoder.py build/app_exe encoded.exe
          python add_hint.py encoded.exe  # Add hint after encoding

      - name: Copy Files to Builds Directory
        run: |
          mkdir -p builds  # Create the builds directory if it doesn't exist
          cp build/encoded.exe builds/encoded.exe
          cp decoder.py builds/decoder.py
          cp hint.txt builds/hint.txt

      - name: Commit and Push Changes
        run: |
          git config --local user.name "GitHub Action"
          git config --local user.email "action@github.com"
          git add builds/
          git commit -m "Add built files"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
